### ISSUE TITLE
~/.textadept/modules/textadept-nim/icons.lua:45: bad argument #1 to 'read' (invalid option)

### ISSUE THREAD

**Issue by survivorm** [xomachine/textadept-nim#3]
After starting textadeptjit i get such error
textadept is 9.6

**Comment by xomachine** [comment]
Never tested it with luajit. Thanks for the report. Please check if it works now.

**Comment by survivorm** [comment]
Looks like it was something external, since now, installed from AUR it works (i'm on arch linux)
