### ISSUE TITLE
Textadept 10.0 alpha language module freezes on Windows

### ISSUE THREAD

**Issue by ledigbick** [xomachine/textadept-nim#4]
Textadept 10.0 alpha freezes on Windows 7 32bit when loading nim source files.
While checking the Task Manager I can see that it spawns a nimsuggest process ("nimsuggest --stdin --debug --v2").
Is there a way to debug the textadept-nim language module?

**Comment by xomachine** [comment]
Well, I can not reproduce it on linux.
All output from nimsuggest is being redirected to stdout as well, so you can check it if textadept is started from command line. It is also possible to add `ui.print`(debug output will appear in textadept buffer) or just `print`(will be printed to stdout) calls into key points of the plugin.

For example you could start from the [nimsuggest session creation](https://github.com/xomachine/textadept-nim/blob/master/sessions.lua#L19) or the [nimble project detection](https://github.com/xomachine/textadept-nim/blob/master/project.lua#L36) code then check how the [plugin parses the nimsuggest output](https://github.com/xomachine/textadept-nim/blob/master/errortips.lua#L10), and so on...

**Comment by ledigbick** [comment]
It seems like the issue under Windows is in [sessions.lua](https://github.com/xomachine/textadept-nim/blob/master/sessions.lua#L51); spawn doesn't execute the process in a separate thread. If I terminate nimsuggest, then textadept unfreezes until nimsuggest gets executed again by pressing '.'. Is it possible to switch from --stdin to --epc?

**Comment by xomachine** [comment]
AFAIK the epc mode means the sockets usage. (I'm not familiar with it) In lua the sockets handling requires additional libraries, so it is not possible without external dependencies.

I wonder if the issue persists in previous versions of textadept under windows. And also it might be a pipe locking problem rather than threading. I will try to reproduce it when set up a windows VM.

**Comment by ledigbick** [comment]
This is trickier than I initially thought. Spawn does execute in a different thread, but in [sessions.lua:102](https://github.com/xomachine/textadept-nim/blob/master/sessions.lua#L102) the main thread blocks once there's no more input to be read (at least under Windows). Newline in Windows is also different, so in [sessions.lua:103](https://github.com/xomachine/textadept-nim/blob/master/sessions.lua#L103) the return string will not be empty but "\r"; reading a line in lua under Windows truncates the "\n" character but the newline sequence in Windows is "\r\n".

**Comment by xomachine** [comment]
Thank you for investigation! I've added some changes including `--tester` mode for nimsuggest which should make parsing eol-insensitive.

**Comment by ledigbick** [comment]
NP, thank you too. I think this issue can be closed, as the freezes are now gone. It still doesn't quite work under Windows, but I suspect it's more because of how Nimsuggest in console mode works under different OSs. I believe you'll have to rewrite the plugin to work with Nimsuggest in EPC mode, eventually. Nimsuggest in EPC mode works almost flawlessly in VS code under Windows.
