### ISSUE TITLE
Just loaded this module and it fails to load

### ISSUE THREAD

**Issue by genotrance** [xomachine/textadept-nim#5]
```
PANIC! Can't open file C:\Users\gt\Desktop\textadept_10.0.win32\...top\textadept_10.0.win32\modules\textadept-nim\images\skTemplate.xpm
...
...
```

Complains about all the xpm files.

**Comment by xomachine** [comment]
Do those files exist in the path where the module is looking for them?

**Comment by genotrance** [comment]
Yes, cloned from github. It doesn't print the entire path so unsure if it is getting the path right.

**Comment by genotrance** [comment]
It looks like the `require "textadept-nim"` isn't really needed per the manual. That being said, while syntax highlighting works, I don't see any of the other features of this module working.

**Comment by xomachine** [comment]
Syntax highlighting works with textadept out-of-box. So this module provides only features listed in the README.

Actually, I can not reproduce the issue in my win10 VM and latest textadept.

**Comment by genotrance** [comment]
I've tried this on two computers, both Win10, with latest nightly and stable.

Steps:
- Download binary ZIP, extract to desktop
- Download modules ZIP and extract to folder\modules
- Git clone textadept-nim to modules folder
- Update init.lua with `require "textadept-nim"`

I now get this error:

```
...IGHTLY_2018-09-12.win32/modules/textadept\file_types.lua:104: attempt to call a nil value (method 'set_lexer')
...s\gt\Desktop\textadept_NIGHTLY_2018-09-12.win32/init.lua:287: attempt to call a nil value (upvalue 'load_settings')
```

If I remove the require, it works just fine.

Please let me know if there's any other info you need to help figure this out.

**Comment by xomachine** [comment]
Well, that is my attempt to reproduce: https://youtu.be/LMrn1sHLY10
The only issue I see is related to the nimsuggest communication.

**Comment by genotrance** [comment]
Okay, it works now but when I try Ctrl-Space or . to auto-complete, I get a messages window with:

```
...NIGHTLY_2018-11-08.win32/modules/textadept-nim\icons.lua:56: bad argument #2 to 'register_image' (string expected, got nil)
```

**Comment by xomachine** [comment]
I finally managed to reproduce the issue. The problem lies in the icons path searching. Now it should be fixed.

**Comment by genotrance** [comment]
Seems to work now.
